"""
Shared setup for the North Sea performance comparison scripts.

All perf_*.py scripts import this module. Run each script from the demos/
directory, e.g.::

    cd demos
    python perf_baseline.py

TPXO tidal forcing data is required (see demo_2d_north_sea.py for details).
If the data directory is absent, a warning is printed and tidal forcing is
omitted — the run will still complete but the solution will be unphysical.

The spinup initial condition (outputs_spinup/) was generated with the default
dg-dg P1DG element family. For other element families, the spinup state is
projected onto the target function spaces.

Note: the spinup was generated by a serial run, so these scripts must also be
run in serial.
"""
import os
import csv
import datetime
import time

from thetis import *
import thetis.coordsys as coordsys
import thetis.forcing as forcing

SIM_TZ = timezone.pytz.utc
COORD_SYSTEM = coordsys.UTMCoordinateSystem(utm_zone=30)

START_DATE = datetime.datetime(2022, 1, 15, tzinfo=SIM_TZ)
END_DATE = datetime.datetime(2022, 1, 18, tzinfo=SIM_TZ)
DT = 3600.0
T_EXPORT = 3600.0
FORCING_CONSTITUENTS = ["Q1", "O1", "P1", "K1", "N2", "M2", "S2", "K2"]

if os.environ.get('THETIS_REGRESSION_TEST'):
    END_DATE = datetime.datetime(2022, 1, 15, 2, tzinfo=SIM_TZ)


def load_mesh_and_bathy():
    """Load mesh and bathymetry from the shared checkpoint file."""
    with CheckpointFile("runfiles/north_sea_bathymetry.h5", "r") as f:
        mesh2d = f.load_mesh("firedrake_default")
        bathymetry_2d = f.load_function(mesh2d, "Bathymetry")
    return mesh2d, bathymetry_2d


def make_physics_fields(mesh2d):
    """Create Manning friction and Coriolis fields on the given mesh."""
    P1_2d = get_functionspace(mesh2d, "CG", 1)

    manning_2d = Function(P1_2d, name="Manning coefficient")
    manning_2d.assign(3.0e-02)

    omega = 7.292e-05
    coriolis_2d = Function(P1_2d, name="Coriolis forcing")
    lon, lat = COORD_SYSTEM.get_mesh_lonlat_function(mesh2d)
    coriolis_2d.interpolate(2 * omega * sin(lat * pi / 180.0))

    return manning_2d, coriolis_2d


def setup_tidal_forcing(mesh2d):
    """
    Create tidal elevation field and boundary forcing callback.

    Returns (elev_tide_2d, update_forcings).  elev_tide_2d should be
    assigned to boundary condition 100 before calling iterate().
    """
    P1_2d = get_functionspace(mesh2d, "CG", 1)
    elev_tide_2d = Function(P1_2d, name="Tidal elevation")

    data_dir = os.path.join(os.environ.get("DATA", "./data"), "tpxo")
    if os.path.exists(data_dir):
        tbnd = forcing.TPXOTidalBoundaryForcing(
            elev_tide_2d,
            START_DATE,
            COORD_SYSTEM,
            data_dir=data_dir,
            constituents=FORCING_CONSTITUENTS,
            boundary_ids=[100],
        )
        tbnd.set_tidal_field(0.0)
    else:
        print_output(f"WARNING: TPXO data not found at {data_dir}. "
                     "Running without tidal forcing.")
        tbnd = None

    def update_forcings(t):
        if tbnd is not None:
            tbnd.set_tidal_field(t)

    return elev_tide_2d, update_forcings


def load_spinup(solver_obj, mesh2d):
    """
    Load the dg-dg P1DG spinup state into solver_obj.

    For element families other than dg-dg degree 1, the elevation and
    velocity fields are projected onto the solver's function spaces.
    """
    with CheckpointFile('outputs_spinup/hdf5/Elevation2d_00014.h5', 'r') as f:
        elev_src = f.load_function(mesh2d, 'elev_2d')
    with CheckpointFile('outputs_spinup/hdf5/Velocity2d_00014.h5', 'r') as f:
        uv_src = f.load_function(mesh2d, 'uv_2d')

    opts = solver_obj.options
    if opts.element_family == 'dg-dg' and opts.polynomial_degree == 1:
        solver_obj.fields.elev_2d.assign(elev_src)
        solver_obj.fields.uv_2d.assign(uv_src)
    else:
        solver_obj.fields.elev_2d.project(elev_src)
        solver_obj.fields.uv_2d.project(uv_src)

    solver_obj.assign_initial_conditions()


def add_station_callbacks(solver_obj):
    """Attach tide-gauge elevation timeseries callbacks."""
    with open("runfiles/stations_elev.csv", "r") as csvfile:
        stations = {
            d["name"]: (float(d["latitude"]), float(d["longitude"]))
            for d in csv.DictReader(csvfile, delimiter=",", skipinitialspace=True)
        }
    for name, (sta_lat, sta_lon) in stations.items():
        sta_x, sta_y = COORD_SYSTEM.to_xy(sta_lon, sta_lat)
        cb = TimeSeriesCallback2D(
            solver_obj, ["elev_2d"], sta_x, sta_y, name, append_to_log=False,
        )
        solver_obj.add_callback(cb)


def run_and_time(solver_obj, update_forcings):
    """Run the model and return wall-clock seconds."""
    t0 = time.perf_counter()
    solver_obj.iterate(update_forcings=update_forcings)
    return time.perf_counter() - t0


def print_performance(solver_obj, wall_time, label):
    """Print a concise performance summary."""
    opts = solver_obj.options
    n_steps = int((END_DATE - START_DATE).total_seconds() / DT)
    dofs_u = solver_obj.function_spaces.U_2d.dim()
    dofs_h = solver_obj.function_spaces.H_2d.dim()
    dofs_total = solver_obj.function_spaces.V_2d.dim()
    print_output("\n" + "=" * 50)
    print_output(f"  {label}")
    print_output("=" * 50)
    print_output(f"  Element family : {opts.element_family}, degree {opts.polynomial_degree}")
    print_output(f"  Timestepper    : {opts.swe_timestepper_type}")
    print_output(f"  DOFs (U_2d)    : {dofs_u}")
    print_output(f"  DOFs (H_2d)    : {dofs_h}")
    print_output(f"  Total DOFs     : {dofs_total}")
    print_output(f"  Timesteps      : {n_steps}")
    print_output(f"  Wall time      : {wall_time:.1f} s")
    print_output(f"  Time / step    : {wall_time / n_steps:.2f} s")
    print_output("=" * 50 + "\n")
