name: Weekly master test

on:
  schedule:
    # Master: 02:30 UTC every Monday
    - cron: '30 2 * * 1'

jobs:
  weekly-master:
    name: Weekly master test
    uses: ./.github/workflows/core.yml
    with:
      branch: master
      image: firedrakeproject/firedrake-vanilla-default:dev-main
    secrets: inherit
