name: Weekly Master Test

on:
  schedule:
    # 02:30 UTC every Monday
    - cron: '30 2 * * 1'

jobs:
  weekly-test:
    uses: ./.github/workflows/core.yml
    with:
      branch: master
      image: firedrakeproject/firedrake-vanilla-default:dev-main
    secrets: inherit
